[package]
name = "granger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.12" }
dirs = { version = "4.0.0" }
rusqlite = { version = "0.27.0", features = ["bundled"] }
toml = { version = "0.5.9" }
serde = { version = "1.0.139", features = ["derive"] }
