[package]
name = "granger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap     = { version = "3.1.18" }
dirs     = { version = "4.0.0" }
rusqlite = { version = "0.27.0", features = ["bundled"] }
